# Generated by Django 2.2.4 on 2019-08-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190831_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='filterpath',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
